[package]
name = "ast"
version = "0.1.0"
edition = "2024"

[dependencies]
span = { path = "../span" }
extract-codeblocks = { path = "../extract-codeblocks" }
serde = { version = "1" }
serde_json = "1.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
textwrap = "0.16"
