default:
  @just --list

build:
    npm ci
    npm run build
    npm run package

install:
    code --install-extension=./out/reqlang-vsc-extension-0.1.0.vsix

uninstall:
    code --uninstall-extension=./out/reqlang-vsc-extension-0.1.0.vsix

clean:
    rm -rf out/* node_modules/

fmt:
    echo "No formatter in place"

lint:
    echo "No linter in place"
