default:
  @just --list

build:
    npm ci
    npm run build
    npm run package

install:
    code --install-extension=./out/reqlang-0.1.0.vsix

uninstall:
    code --list-extensions | grep reqlang | xargs -I {} code --uninstall-extension={}

clean:
    rm -rf out/* node_modules/

format:
    npm run format
    npm run lint:fix

check:
    npm run lint
    npm run format:check

test:
    npm run test